/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclesalesmanagement;

import com.placeholder.PlaceHolder;
import groovy.model.DefaultTableModel;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author it17153232
 */
public class Accounts extends javax.swing.JPanel {

    /**
     * Creates new form Accounts
     */
    public Accounts() {
        initComponents();
        GenerateCurrentDateAccounts();
        jLabel3.setText(Integer.toString(0));
        comboyearload();
        comboyearload2();
        combo3Monthload();
        
        jLabel8.setText(Integer.toString(0));
        jLabel14.setText(Integer.toString(0));
        jButton1.setEnabled(false);
        jTextField1.setText("daily Accounts");
         PlaceHolder ob3 = new PlaceHolder(jTextField2,"Invoice Barcode");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        jTabbedPane1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model", "Selling Price", "Given Price", "Cash", "Balance", "Cost Price", "Profit", "Selling Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 640));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateChooserCombo1.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        try {
            dateChooserCombo1.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }
        dateChooserCombo1.setCurrentNavigateIndex(0);
        dateChooserCombo1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateChooserCombo1OnSelectionChange(evt);
            }
        });
        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel2.add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 14, 200, 34));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel1.setText("Profit By Date");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 118, 34));

        jToggleButton1.setBackground(new java.awt.Color(255, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jToggleButton1.setText("Total Sales");
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel3.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 54, 118, 80));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 40));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Total Profit For Current Date");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 344, 145));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton2.setBackground(new java.awt.Color(51, 255, 0));
        jToggleButton2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jToggleButton2.setText("Total Sales");
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel8.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel6.setText(" Profit By Year");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 118, 31));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 14, 196, 31));

        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 51, 118, 83));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setText("Total Profit For Current Year");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 154, 344, 149));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel11.setText("Profit By Month");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 118, 26));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 14, 113, 26));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox3MousePressed(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 14, 77, 26));

        jToggleButton3.setBackground(new java.awt.Color(255, 255, 51));
        jToggleButton3.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jToggleButton3.setText("Total Sales");
        jPanel4.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Total Profit For Current Month");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        jLabel14.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 46, 118, 94));

        jLabel15.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 309, 344, 148));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 40, 40));

        jToggleButton5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jToggleButton5.setText("      Show All Accounts");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 160, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 30, 40));

        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton1.setText("     Print All Accounts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 160, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 40, 40));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 255));
        jButton2.setText("     Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 130, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer_add.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 30, 40));

        jButton6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton6.setText("       Print Selected Format");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 190, 40));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Digital-7", 0, 24)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 330, 40));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 350, 640));

        jTabbedPane1.addTab("Vehicle Selling Accounts", jLayeredPane1);

        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model", "Quantity", "Selling_price", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel20.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 0));
        jLabel23.setText("Sub Total -");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField3.setEditable(false);

        jLayeredPane2.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(659, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BodyParts Selling Accounts", jLayeredPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserCombo1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnSelectionChange
        
         javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        
        try {
            ResultSet rs = Database.getData("select * from sale where selling_date='"+dateChooserCombo1.getText()+"'");
            while(rs.next()){
                
                Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                dtm.addRow(v);
            
            
            
            }
            
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_dateChooserCombo1OnSelectionChange

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
            jComboBox1.setEnabled(false);
             jComboBox2.setEnabled(false);
              jComboBox3.setEnabled(false);
              jTextField1.setText(dateChooserCombo1.getText());
            
              //String t = new SimpleDateFormat("MMM dd, yyyy").format(new Date());
              
              
              
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        double profit = 0;
        try {
            ResultSet rs = Database.getData("select * from sale where selling_date='"+dateChooserCombo1.getText()+"'");
            while(rs.next()){
                
                Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                dtm.addRow(v);
                profit+=rs.getDouble("profit");
           
            
            
            }
            
            
            
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        jLabel4.setText(Double.toString(profit));
        
        //-------------------------------------------------------------------------
        
         try {
            ResultSet rs = Database.getData("select count(*) as total  from sale where selling_date='"+dateChooserCombo1.getText()+"'");
            while(rs.next()){
                
                jLabel3.setText(Integer.toString(rs.getInt("total")));
            
            
            
            }
            
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
            dateChooserCombo1.setEnabled(false);
             jComboBox2.setEnabled(false);
              jComboBox3.setEnabled(false);
              jTextField1.setText(jComboBox1.getSelectedItem().toString());
            
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        double profit = 0;
        try {
            ResultSet rs= Database.getData("SELECT * FROM sale WHERE selling_date LIKE '"+"%"+jComboBox1.getSelectedItem()+"'");
            while (rs.next()) {                
                Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                dtm.addRow(v);
                 profit+=rs.getDouble("profit");
                
                
            }
        } catch (Exception e) {
        }
         jLabel10.setText(Double.toString(profit));
        
        //---------------------------------------------------------------------------------------
          try {
            ResultSet rs= Database.getData("SELECT count(*) as total2 FROM sale WHERE selling_date LIKE '"+"%"+jComboBox1.getSelectedItem()+"'");
            while (rs.next()) {                
                
            
                jLabel8.setText(Integer.toString(rs.getInt("total2")));
                
            }
        } catch (Exception e) {
        }
        
        
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
     
          javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
         double profit = 0;
        if(jComboBox2.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(null,"Select Year First !");
           
       }else{
           
           try {
               
               ResultSet rs = Database.getData("SELECT * FROM sale WHERE selling_date LIKE  '" + "%" + jComboBox2.getSelectedItem()+"' and selling_date LIKE '" + jComboBox3.getSelectedItem() + "%" + "'");
               while (rs.next()) {                   
                   
                    Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                profit+=rs.getDouble("profit");
                dtm.addRow(v);
                   
               }
               
               
           } catch (Exception e) {
               
               e.printStackTrace();
           }
           jLabel15.setText(Double.toString(profit));
       
       
           //------------------------------------------------------------
           
            try {
               
               ResultSet rs = Database.getData("SELECT count(*) as total3 FROM sale WHERE selling_date LIKE  '" + "%" + jComboBox2.getSelectedItem()+"' and selling_date LIKE '" + jComboBox3.getSelectedItem() + "%" + "'");
               while (rs.next()) {                   
                   
                    jLabel14.setText(Integer.toString(rs.getInt("total3")));
                   
                   
               }
               
               
           } catch (Exception e) {
               
               e.printStackTrace();
           }
           
           
           
       }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
                   javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        if(jToggleButton5.isSelected()==true){
            
        
        
        
        try {
            
            String d = new SimpleDateFormat("MMM dd, yyyy").format(new Date());
            ResultSet rs = Database.getData("select * from sale ");
            
            while(rs.next()){
                
                Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                dtm.addRow(v);
            
            
            
            }
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        jButton1.setEnabled(true);
       
       }else if(jToggleButton5.isSelected()==false){
       
            jButton1.setEnabled(false);
            dtm.setRowCount(0);
            
            
       
       }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        
       
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path1 = "C:\\Users\\it17153232\\Desktop\\Vehicle Sale Project\\Project\\VehicleSalesManagement\\src\\Reports\\VehicleSalesAccountsAll.jrxml";

 try {
                javax.swing.table.DefaultTableModel df = ( javax.swing.table.DefaultTableModel ) jTable1.getModel();
                JRTableModelDataSource dataSource = new JRTableModelDataSource(df);
                
                JasperReport jr = JasperCompileManager.compileReport(path1);
                Map params = new HashMap();
                params.put("dt","All Accounts");
                
                
              
                
           
                JasperPrint jp = JasperFillManager.fillReport(jr, params, dataSource);
                JasperViewer.viewReport(jp,false);
                
                
            } catch (JRException ex) {
               ex.printStackTrace();
            } 
        
            
 

        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
      dateChooserCombo1.setEnabled(false);
      
             jComboBox1.setEnabled(false);
             
              jTextField1.setText(jComboBox2.getSelectedItem().toString()+","+jComboBox3.getSelectedItem().toString());     
            
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dateChooserCombo1.setEnabled(true);
             jComboBox2.setEnabled(true);
              jComboBox3.setEnabled(true);
               jComboBox1.setEnabled(true);
               jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MousePressed
        jTextField1.setText(jComboBox2.getSelectedItem().toString()+","+jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox3MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
        
        if(jTable1.getRowCount()==0){
        
                JOptionPane.showMessageDialog(null,"There Are No Accounts To Print");
        
        }else{
            
            String path1 = "C:\\Users\\it17153232\\Desktop\\Vehicle Sale Project\\Project\\VehicleSalesManagement\\src\\Reports\\VehicleSalesAccountsAll.jrxml";

 try {
                javax.swing.table.DefaultTableModel df = ( javax.swing.table.DefaultTableModel ) jTable1.getModel();
                JRTableModelDataSource dataSource = new JRTableModelDataSource(df);
                
                JasperReport jr = JasperCompileManager.compileReport(path1);
                Map params = new HashMap();
                params.put("dt",jTextField1.getText());
                
                
              
                
           
                JasperPrint jp = JasperFillManager.fillReport(jr, params, dataSource);
                JasperViewer.viewReport(jp,false);
                
                
            } catch (JRException ex) {
               ex.printStackTrace();
            } 
        
            
 
        
        
        }
        
        
        
        
        
        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
       
        String cid = null;
        String did = null;
         String brand = null;
        String sprice = null;
          javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        
        //------------------------------------------------------------------------------------------------
        
        try {
            ResultSet rs = Database.getData("select * from  bodypratselling where invoice_id='"+jTextField2.getText()+"'");
            while (rs.next()) {
                
                 cid = rs.getString("cusid");
                brand=rs.getString("brand");
                    
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
        
        
        //----------------------------------------------------------------------------------
        
        
         try {
            ResultSet rs = Database.getData("select * from  customer where cid='"+cid+"'");
            while (rs.next()) {
                
                 did = rs.getString("did");
                
                    
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
         
         //-----------------------------------------------------------------------
         
         int rate;
          try {
            ResultSet rs = Database.getData("select * from  discount where d_id='"+did+"'");
            while (rs.next()) {
                
                 rate =rs.getInt("rate");
                jLabel20.setText("Discount - "+Integer.toString(rate)+"%");
                    
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
          
        //----------------------------------------------------------------------  
       
         try {
            ResultSet rs = Database.getData("select * from  body_parts where brand='"+brand+"'");
            while (rs.next()) {
                
              sprice=rs.getString("price");
              
              
                
                    
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
       
        
        
        
        //------------------------------------------------------------------------
        
        
        
         //-----------------------------------------------------------
         
           try {
            ResultSet rs = Database.getData("select * from  bodypratselling where invoice_id='"+jTextField2.getText()+"'");
            while (rs.next()) {
                
              Vector v = new Vector();
              v.add(rs.getString("brand"));
              
              
              v.add(rs.getString("model"));
               v.add(rs.getString("quantity"));
               v.add(sprice);
                v.add(rs.getString("total"));
                dtm.addRow(v);
              
              
                
                    
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
           
        //-----------------------------------------
        
        
        int b=0;
        for(int i=0;i<dtm.getRowCount();i++){
        
          String s= (String) dtm.getValueAt(i, 4);
            
            b=Integer.valueOf(s);
            b+=b;
                    
            
        
        }
       jTextField3.setText(Integer.toString(b));
                    
        
        
          
        
        
        
        
        
    }//GEN-LAST:event_jTextField2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables

    private void GenerateCurrentDateAccounts() {
       javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        
        try {
            
            String d = new SimpleDateFormat("MMM dd, yyyy").format(new Date());
            ResultSet rs = Database.getData("select * from sale where selling_date='"+d+"'");
            
            while(rs.next()){
                
                Vector v = new Vector();
                v.add(rs.getString("brand"));
                v.add(rs.getString("model"));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("givenPrice"));
                
                 v.add(rs.getString("cash"));
                v.add(rs.getString("balance"));
                v.add(rs.getString("cost_price"));
                v.add(rs.getString("profit"));
                v.add(rs.getString("selling_date"));
                dtm.addRow(v);
            
            
            
            }
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void comboyearload() {
       
        jComboBox1.addItem("2016");
        jComboBox1.addItem("2017");
        jComboBox1.addItem("2018");
          jComboBox1.addItem("2019");
            jComboBox1.addItem("2020");
              jComboBox1.addItem("2021");
                jComboBox1.addItem("2022");
                  jComboBox1.addItem("2023");
                    jComboBox1.addItem("2024");
        jComboBox1.addItem("2025");
        jComboBox1.addItem("2026");
          jComboBox1.addItem("2027");
            jComboBox1.addItem("2028");
              jComboBox1.addItem("2029");
                jComboBox1.addItem("2030");
                  jComboBox1.addItem("2031");
                  
                  
        
        
        
        
    }

    private void comboyearload2() {
        
          jComboBox2.addItem("2016");
        jComboBox2.addItem("2017");
        jComboBox2.addItem("2018");
          jComboBox2.addItem("2019");
            jComboBox2.addItem("2020");
              jComboBox2.addItem("2021");
                jComboBox2.addItem("2022");
                  jComboBox2.addItem("2023");
                    jComboBox2.addItem("2024");
        jComboBox2.addItem("2025");
        jComboBox2.addItem("2026");
          jComboBox2.addItem("2027");
            jComboBox2.addItem("2028");
              jComboBox2.addItem("2029");
                jComboBox2.addItem("2030");
                  jComboBox2.addItem("2031");
                  
        
        
    }

    private void combo3Monthload() {
            
          jComboBox3.addItem("Jan");
        jComboBox3.addItem("Feb");
        jComboBox3.addItem("Mar");
          jComboBox3.addItem("Apr");
            jComboBox3.addItem("May");
              jComboBox3.addItem("Jun");
                jComboBox3.addItem("Jul");
                  jComboBox3.addItem("Aug");
                    jComboBox3.addItem("Sep");
                    jComboBox3.addItem("Oct");
                    jComboBox3.addItem("Nov");
                    jComboBox3.addItem("Dec");
                    
        
        
        
    }
}
