/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclesalesmanagement;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author it17153232
 */
public class BodyParts_brand extends javax.swing.JFrame {

    /**
     * Creates new form BodyParts_brand
     */
    public BodyParts_brand() {
        initComponents();
        comboload();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 40, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("     Add Brand");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 270, 50));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Body Parts Brand Manager");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 240, 20));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 270, 190));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 240, 50));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 240, 50));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 260, 190));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 240, 50));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 260, 190));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Add");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 30, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Update");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Delete");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 260, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 260, 50));

        jButton4.setText("ADD DEMO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            
            ResultSet alredy_brand = Database.getData("SELECT * FROM bodypartbrand WHERE bodypartbrand.brandName = '"+jTextField1.getText()+"'");
        
        if(alredy_brand.next()){
        
            JOptionPane.showMessageDialog(null, "this brand already in the system!");
        
        }else{
        
        
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Select Category")){
          JOptionPane.showMessageDialog(null, "please select category befor add!");
      
      }else{
            
            
            try {
            Database.setData("insert into BodyPartBrand values('0','"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem()+"')");
            JOptionPane.showMessageDialog(null,"Brand Successfully Added To System");
            jTextField1.setText(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
            
            
            
            
           autoBrandReder();
           comboload();
      
      }
            
            
        }
        
        
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      
      
    
           autoBrandReder();
      
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            
            ResultSet rs = Database.getData("SELECT * FROM bodypartbrand WHERE bodypartbrand.brandName ='"+jComboBox3.getSelectedItem()+"'");
            
            if(rs.next()){
                String brand = rs.getString(2);
                String stat = rs.getString(3);
                System.out.println(stat);
                
                if(stat.equalsIgnoreCase("AlloyWheel")){
                
                    ResultSet al_rs = Database.getData("SELECT * FROM body_parts,bodypartbrand,bodymodel,alloywheel WHERE body_parts.brand = bodypartbrand.brandName AND bodypartbrand.bid=bodymodel.bid AND body_parts.bid=alloywheel.bid AND bodypartbrand.brandName ='"+brand+"' ");
                    
                    if(al_rs.next()){
                    
                    //Database.setData("INSERT INTO remove_bodyparts (brand,modeNum,model,status,price,size,rimMaterial,discript,amphere,hrtz,cost_price) VALUES('"+al_rs.getString(2)+"','"+al_rs.getString(3)+"','"+al_rs.getString(5)+"','"+al_rs.getString(11)+"','"+al_rs.getString(7)+"','"+al_rs.getString(18)+"','"+al_rs.getString(19)+"','---','---','---','"+al_rs.getString(8)+"')");
                    
                        Database.setData("DELETE FROM body_parts WHERE body_parts.bid ='"+al_rs.getString(1)+"'");
                        Database.setData("DELETE FROM bodypartbrand WHERE bodypartbrand.bid ='"+al_rs.getString(9)+"'");
                        Database.setData("DELETE FROM bodymodel WHERE bodymodel.m_id ='"+al_rs.getString(12)+"'");
                        Database.setData("DELETE FROM alloywheel WHERE alloywheel.a_id ='"+al_rs.getString(16)+"'");
                        JOptionPane.showMessageDialog(null, "Deleted!");
                        
                    }
                    
                }else if(stat == "Multimedia"){
                
                    
                }else if(stat == "Accessories"){
                
                }
                
                
                
                
              //  Database.setData("INSERT INTO remove_bodyparts (brand,modeNum,model,status,price,size,rimMaterial,discript,amphere,hrtz,cost_price) "
               //     + "VALUES('"++"','"++"','"++"','"++"','"++"','"++"','"++"','"++"','"++"','"++"','"++"')");

                
            }
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
       
        try {
            Database.setData("UPDATE bodypartbrand,body_parts SET bodypartbrand.brandName = '"+jTextField2.getText()+"',body_parts.brand='"+jTextField2.getText()+"' WHERE bodypartbrand.brandName='"+jComboBox2.getSelectedItem()+"'AND body_parts.brand='"+jComboBox2.getSelectedItem()+"'");
            JOptionPane.showMessageDialog(null, "Updated!");
            autoBrandReder();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        jTextField1.setText("JVC");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());

        } catch (Exception e) {
            e.printStackTrace();

        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BodyParts_brand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void comboload() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Select Category");
        jComboBox1.addItem("AlloyWheel");
        jComboBox1.addItem("Multimedia");
        jComboBox1.addItem("Accessories");
        
        
        
        
        
    }
    private void autoBrandReder(){
    
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Select Brand");
        
        jComboBox3.removeAllItems();
        jComboBox3.addItem("Select Brand");
        try {
            ResultSet brand_rs = Database.getData("SELECT bodypartbrand.brandName FROM bodypartbrand WHERE bodypartbrand.status='"+jComboBox1.getSelectedItem()+"'");
            
            while(brand_rs.next()){
            
                jComboBox2.addItem(brand_rs.getString(1));
                jComboBox3.addItem(brand_rs.getString(1));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
}
