/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclesalesmanagement;

import com.mysql.jdbc.MysqlDataTruncation;
import java.awt.Image;
import java.awt.image.VolatileImage;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.Year;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import javafx.beans.binding.Bindings;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.regex.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import static vehiclesalesmanagement.Registerd_Vehicle.path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrintManager;
import static vehiclesalesmanagement.Registerd_Vehicle.path;

/**
 *
 * @author Vihanga
 */
public class Exchange_vehicle extends javax.swing.JPanel {

    /**
     * Creates new form Exchange_vehicle
     */
    public Exchange_vehicle() {
     
        initComponents();
        brandload();
        typeload();
        statusload();
        customerload();
        registerdCount();
        unregisterdcount();
        exchangecount();
       
        jProgressBar1.setVisible(false);
       
       
    }
    static String path2 = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        REGISTERD = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel66 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel68 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("UNREGISTERD");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, -1));

        REGISTERD.setBackground(new java.awt.Color(255, 204, 0));
        REGISTERD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        REGISTERD.setText("REGISTERD");
        REGISTERD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERDActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTERD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        jToggleButton2.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton2.setText("EXCHANGE");
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, -1));

        jLabel66.setBackground(new java.awt.Color(102, 204, 0));
        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 90, 40));

        jLabel64.setBackground(new java.awt.Color(255, 204, 204));
        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 40));

        jLabel65.setBackground(new java.awt.Color(204, 204, 0));
        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, 40));

        jLabel61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 70));

        jLabel63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, 70));

        jLabel62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 70));

        jLabel59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 169, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-left.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 51, 30));

        jLabel60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 60));

        jButton10.setBackground(new java.awt.Color(102, 255, 51));
        jButton10.setForeground(new java.awt.Color(255, 255, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator_1.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("DEMO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 40));

        jButton9.setBackground(new java.awt.Color(51, 255, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 0, 51));
        jButton9.setText("Search all");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 51), null, null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 360, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 255), null));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("NIC Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Customer name");

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Phone Number");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Book Registration");

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/monitor-sidebar.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Customer" }));
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/we.gif"))); // NOI18N

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel70.setText("         Customer Details");
        jLabel70.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, 0, 175, Short.MAX_VALUE)
                            .addComponent(jTextField8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField8)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 360, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Brand");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 136, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Model Year");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 80, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 136, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Model");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 50, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 136, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Engine (CC)");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 90, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 136, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Mileage  (Km)");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 100, 30));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 136, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Chassis Number");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 136, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Register Number");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 30));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 140, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Engine Number");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 30));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 140, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Selling Price(Rs)");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, 30));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Type");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 60, 30));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 140, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Status");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 60, 30));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 140, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Discription");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 210, 120));

        jLabel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 290, 120));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel67.setText("                         System Vehicle");
        jLabel67.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel67.setMaximumSize(new java.awt.Dimension(239, 17));
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 530, 460));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Brand");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Model Year");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        jTextField9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Model");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Engine(CC)");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        jTextField10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Mileage  (Km)");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Chassis Number");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));

        jTextField11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 30));

        jTextField12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText(" Register Number");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 30));

        jTextField13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 150, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Engine Number");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 120, 30));

        jTextField14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 150, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Selling Price  (Rs)");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 30));

        jTextField15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Type");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 90, 30));

        jComboBox3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Status");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 90, 30));

        jComboBox4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 150, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Discription");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 90, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 150, 110));

        jLabel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 250, 130));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/monitor-sidebar.png"))); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sync.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 30, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("   Convert Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 170, 50));
        jPanel4.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 250, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "eBrand", "gBrand", "eModel", "gModel", "exchangeDate", "balance", "ePrice", "gPrice", "eType", "gType", "book_Image", "e_id"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 590, 0));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel68.setText("                          Customer Vehicle");
        jLabel68.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 249, 590, 460));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 102), null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setText(" (Km) Difference");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 110, 33));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, 33));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 0));
        jLabel52.setText("      System");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 93, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 51, 51));
        jLabel53.setText(" Exchange");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 76, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setText("  Year Difference ");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 49, 160, 33));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setText(" Balance (Rs)");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 43));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 43));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_file_documents-16_854147.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 40));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer_add.png"))); // NOI18N
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 40, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("    Approve Exchange");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 47));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("        Print Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 170, 47));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 400, 250));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 1110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                      //  jProgressBar1.setValue(i);
                        //jProgressBar1.setVisible(true);
                        jLabel69.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (NullPointerException e) {
                            JOptionPane.showMessageDialog(null, "Please select Valide Image","Image Not Selected",1);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Registerd_Vehicle.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    jLabel10.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH)));
                   jProgressBar1.setVisible(false);
                    jLabel69.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                        jProgressBar1.setValue(i);
                        jProgressBar1.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    jLabel47.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel47.getWidth(), jLabel47.getHeight(), Image.SCALE_SMOOTH)));
                    jProgressBar1.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       try {
            int result = Integer.valueOf(jLabel20.getText()) - Integer.valueOf(jTextField11.getText());
            jLabel54.setText(Double.toString(result));
            if(result<0)
            {
             JOptionPane.showMessageDialog(null, "User Vehicle Mileage is Grater Than System Vehicle");   
            }
            
            

        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please Fill the exchange Vehicle Details");

        } catch (Exception e) {

        }

        try {
            int result = Integer.valueOf(jLabel28.getText()) - Integer.valueOf(jTextField15.getText());
            jLabel57.setText(Double.toString(result));

        } catch (java.lang.NumberFormatException ex) {
            //JOptionPane.showMessageDialog(null, "Please Enter Only Price");

        } catch (Exception e) {

        }

        
     
        



         String modelyear= "[0-9]{4}";
         modelyear=jTextField9.getText();
      //String sPhoneNumber = "605-88899991";
      //String sPhoneNumber = "605-888999A";

      Pattern pattern = Pattern.compile("[0-9]{4}");
      Matcher matcher = pattern.matcher(modelyear);

      if (matcher.matches()) {
          // jTextField9.setEditable(false);
         jLabel50.setText(jLabel14.getText());
         jLabel51.setText(jTextField9.getText());
         
      } else {
          JOptionPane.showMessageDialog(null,"Invalid Model year");
          jTextField9.setEditable(true);
             jLabel50.setText(null);
         jLabel51.setText(null);
      }     
            String engine= "^[0-9]{3,4}$";
         engine=jTextField10.getText();
      //String sPhoneNumber = "605-88899991";
      //String sPhoneNumber = "605-888999A";

      Pattern pattern1 = Pattern.compile("^[0-9]{3,4}$");
      Matcher matcher1 = pattern1.matcher(engine);

      if (matcher1.matches()) {
         
         
      } else {
          JOptionPane.showMessageDialog(null,"Invalid Engine(CC)");
          jTextField10.setEditable(true);
             jLabel50.setText(null);
         jLabel51.setText(null);
      }  
             String mileage= "^[0-9]*$";
        mileage=jTextField11.getText();
      //String sPhoneNumber = "605-88899991";
      //String sPhoneNumber = "605-888999A";

      Pattern pattern2 = Pattern.compile("^[0-9]*$");
      Matcher matcher2 = pattern2.matcher(mileage);

      if (matcher2.matches()) {
         jTextField11.setEditable(false);
              } else {
          JOptionPane.showMessageDialog(null,"Invalid Mileage(Km) ");
          jTextField11.setEditable(true);
             jLabel50.setText(null);
         jLabel51.setText(null);
      }
            
             String selling= "^[0-9]*$";
        selling=jTextField15.getText();
      //String sPhoneNumber = "605-88899991";
      //String sPhoneNumber = "605-888999A";

      Pattern pattern3 = Pattern.compile("^[0-9]*$");
      Matcher matcher3 = pattern3.matcher(selling);

      if (matcher3.matches()) {
        
         
      } else {
          JOptionPane.showMessageDialog(null,"Invalid Selling Price ");
          jTextField15.setEditable(true);
             jLabel50.setText(null);
         jLabel51.setText(null);
      }
      /*
               String regnum;
               regnum="[A-Z{3} 0-9{7}   ]+\\\\?";
        regnum=jTextField13.getText();
      //String sPhoneNumber = "605-88899991";
      //String sPhoneNumber = "605-888999A";

      Pattern pattern4 = Pattern.compile("[A-Z{3} 0-9{7}  ]+\\\\?");
      Matcher matcher4 = pattern4.matcher(regnum);

      if (matcher4.matches()) {
        //
         
      } else {
          JOptionPane.showMessageDialog(null,"Invalid Register Number ");
          jTextField13.setEditable(true);
             jLabel50.setText(null);
         jLabel51.setText(null);
      }
      */
      
         if(jTextField13.getText().matches("^[A-Z]{2,3}$")){
               //
               }
        
       if (jTextField13.getText().length() == 8|| jTextField13.getText().length() == 7) {
         
                if (jTextField13.getText().charAt(4) == '-' ) {
                   // System.out.println(jTextField13.getText().charAt(4));
                   // System.out.println(jTextField13.getText().charAt(3));
                }
                    
              
            }
      else if (jTextField13.getText().length() == 7) {
         

                if (jTextField13.getText().charAt(3) == '-' ) {
                   // System.out.println(jTextField13.getText().charAt(4));
                   // System.out.println(jTextField13.getText().charAt(3));
                } 
      } else {
                JOptionPane.showMessageDialog(null, "Invalid Register Number ");
                jLabel50.setText(null);
         jLabel51.setText(null);
            }
     
      
      
       calculation(); 
       
    
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
      
    }//GEN-LAST:event_jTextField1KeyReleased
    String imgp;
    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
long count = 0;  

String search = jTextField1.getText();
        
       
            //String search =search_tf.getText();
            if (search.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null,"Please fill the Search Method as Chassis Number OR Register OR Engine Number");
                 jLabel12.setText(null);
                    jLabel14.setText(null);
                    jLabel16.setText(null);
                    jLabel18.setText(null);
                    jLabel20.setText(null);
                    jLabel22.setText(null);
                    jLabel24.setText(null);
                    jLabel26.setText(null);
                    jLabel28.setText(null);
                    jLabel30.setText(null);
                    jLabel32.setText(null);
                    jTextArea1.setText(null);
                    jLabel34.setText(null);
                
            } else {
               

                try {

                        ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE regNum LIKE '%" + search + "%' "
                            + "OR chassisNum LIKE '"+search+"%' OR engNum LIKE '"+search+"%'  ");
                    while (rs.next()) {
                    //System.out.println("Testing Sucess");
                    jLabel12.setText(rs.getString(2));
                    jLabel14.setText(rs.getString(3));
                    jLabel16.setText(rs.getString(4));
                    jLabel18.setText(rs.getString(6));
                    jLabel20.setText(rs.getString(7));
                    jLabel22.setText(rs.getString(8));
                    jLabel24.setText(rs.getString(13));
                    jLabel26.setText(rs.getString(5));
                    jLabel28.setText(rs.getString(9));
                    jLabel30.setText(rs.getString(12));
                    jLabel32.setText(rs.getString(16));
                    jTextArea1.setText(rs.getString(11));

                    String n = rs.getString(10);
                    String x = n.replace('/', '\\');
                    imgp = x;

                    if (new File(n).exists()) {
                        jLabel34.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), Image.SCALE_SMOOTH)));
                    } else {
                        JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
                    }

                    count = 1;

                }

                if (count == 1) {

                } else {
                    JOptionPane.showMessageDialog(null, "Data not found");

                }

            } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, e);
                }
            }
       
    }//GEN-LAST:event_jButton4ActionPerformed
   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
long count = 0;  

String search = jTextField1.getText();
        
       
            //String search =search_tf.getText();
            if (search.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null,"Please fill the Search Method as Chassis Number OR Register OR Engine Number");
                 jLabel12.setText(null);
                    jLabel14.setText(null);
                    jLabel16.setText(null);
                    jLabel18.setText(null);
                    jLabel20.setText(null);
                    jLabel22.setText(null);
                    jLabel24.setText(null);
                    jLabel26.setText(null);
                    jLabel28.setText(null);
                    jLabel30.setText(null);
                    jLabel32.setText(null);
                    jTextArea1.setText(null);
                    jLabel34.setText(null);
                   
                
            } else {
               

                try {

                        ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE regNum LIKE '%" + search + "%' "
                            + "OR chassisNum LIKE '"+search+"%' OR engNum LIKE '"+search+"%'  ");
                        
                    if (rs.next()) {
                        
                        ResultSet in_rs = Database.getData("SELECT * FROM vehicle,model WHERE model.model = vehicle.model AND vehicle.v_id ='"+rs.getString("v_id")+"'");
                        
                        if(in_rs.next()){
                        
                            
                            //System.out.println("Testing Sucess");
                    jLabel12.setText(in_rs.getString("brand"));//BRAND
                    jLabel14.setText(in_rs.getString("modelYear"));//MODLE YEAR
                    jLabel16.setText(in_rs.getString("model"));//MODLE
                    jLabel18.setText(in_rs.getString("engCap"));//ENG CC
                    jLabel20.setText(in_rs.getString("mileage"));//MILAGE
                    jLabel22.setText(in_rs.getString("chassisNum"));//CHASSIS
                    jLabel24.setText(in_rs.getString("regNum"));//REG NUM
                    jLabel26.setText(in_rs.getString("engNum"));//ENG NUM
                    jLabel28.setText(in_rs.getString("sPrice"));//SELLING PRI
                    jLabel30.setText(in_rs.getString("type"));//TYPE
                    jLabel32.setText(in_rs.getString("status"));//STATUS
                    jTextArea1.setText(in_rs.getString("discription"));//DISCRIPTION

                    String n = in_rs.getString("vImage");//IMGE
                    String x = n.replace('/', '\\');
                    imgp = x;

                    if (new File(n).exists()) {
                        jLabel34.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), Image.SCALE_SMOOTH)));
                    } else {
                        JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
                    }

                    count = 1;
                        }else{}
                    

                }

                if (count == 1) {

                } else {
                    JOptionPane.showMessageDialog(null, "Data not found");

                }

            } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, e);
                }
            }
       
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.removeAllItems();
        String s = null;
        try {

            ResultSet rs1 = Database.getData("select bid from brand where Brand_name='" + jComboBox1.getSelectedItem() + "'  order by bid asc");

            //System.out.println(s);
            if (rs1.next()) {

                s = rs1.getString("bid");
                //System.out.println(s);

            }

            ResultSet rs = Database.getData("select m.model from brand b,model m where m.bid='" + s + "' group by m.bid,m.model ");

            while (rs.next()) {

                jComboBox2.addItem(rs.getString("m.model"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased

    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped

    }//GEN-LAST:event_jTextField11KeyTyped

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked


    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        try {
            ResultSet rs = Database.getData("select * from customer where NIC='" + jComboBox5.getSelectedItem() + "'");
            if (rs.next()) {

                jTextField7.setText(rs.getString(5));
                jTextField7.setEditable(false);
                jTextField8.setText(rs.getString(4));
                 jTextField8.setEditable(false);

            }
            else if(jComboBox5.getSelectedItem().equals("Select Customer"))
            {
                jTextField7.setText(null);
                jTextField7.setEditable(true);
                jTextField8.setText(null);
                 jTextField8.setEditable(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (jLabel57.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "first convert the info!");

        } else if (jComboBox5.getSelectedItem().toString().equalsIgnoreCase("Select Customer")) {
            JOptionPane.showMessageDialog(null, "first select the NIC!");

        } else {

            //exchange vehicle
            String vBookImg = "null";
            String vimag = "null";
            String vid = "null";
            String t = new SimpleDateFormat("MMM dd, yyyy").format(new Date());
            String rpnew = path2.replace('\\', '/');
            String rp = path.replace('\\', '/');
            String cid = "null";

            try {

                Database.setData("insert into exchangeveh(eBrand,gBrand,eModel,gModel,exchangeDate,balance,ePrice,gPrice,eType,gType,book_Image) values('" + jComboBox1.getSelectedItem() + "','" + jLabel12.getText() + "','" + jComboBox2.getSelectedItem() + "','" + jLabel16.getText() + "','" + t + "','" + jLabel57.getText() + "','" + jTextField15.getText() + "','" + jLabel28.getText() + "','" + jComboBox3.getSelectedItem() + "','" + jLabel30.getText() + "','" + rpnew + "')");
                JOptionPane.showMessageDialog(null, "Echanged Vehicle Sucess !");
                System.out.println(jLabel28.getText());
            } catch (Exception e) {
                e.printStackTrace();
            }

            // removed vehicle 
            try {

                ResultSet vBook_rs = Database.getData("select * from vehicle where chassisNum='" + jLabel22.getText() + "'");
                if (vBook_rs.next()) {
                    vBookImg = vBook_rs.getString(14);
                    vimag = vBook_rs.getString(10);
                    vid = vBook_rs.getString(1);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            try {

                Database.setData("insert into removevehi (status,brand,modelYear,model,engNum,engCap,mileage,chassisNum,sPrice,vImage,discription,type,regNum,vBoolImg) values ('Exchange','" + jLabel12.getText() + "','" + jLabel14.getText() + "','" + jLabel16.getText() + "','" + jLabel26.getText() + "','" + jLabel18.getText() + "','" + jLabel20.getText() + "','" + jLabel22.getText() + "','" + jLabel28.getText() + "','" + vimag + "','" + jTextArea1.getText() + "','" + jLabel30.getText() + "','" + jLabel24.getText() + "','" + vBookImg + "')");
                Database.setData("delete  from vehicle where v_id ='" + vid + "' ");
            } catch (Exception e) {
                e.printStackTrace();
            }

            //vehicle inset quary and throws the details to removedveh table
            try {
                ResultSet cid_rs = Database.getData("select * from customer where NIC  ='" + jComboBox5.getSelectedItem() + "' ");

                if (cid_rs.next()) {
                    cid = cid_rs.getString(1);
                }
            } catch (Exception e) {
            }

            // insert values for vehicle table from exchange vehicle
            try {

                Database.setData("insert into vehicle(brand,modelYear,model,engNum,engCap,mileage,chassisNum,sPrice,vImage,discription,type,regNum,vBoolImg,c_id,status) values('" + jComboBox1.getSelectedItem() + "','" + jTextField9.getText() + "','" + jComboBox2.getSelectedItem() + "','" + jTextField14.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "','" + jTextField12.getText() + "','" + jTextField15.getText() + "','" + rp + "','" + jTextArea2.getText() + "','" + jComboBox3.getSelectedItem() + "','" + jTextField13.getText() + "','" + rpnew + "','" + cid + "','" + jComboBox4.getSelectedItem() + "')");
                JOptionPane.showMessageDialog(null, "Exchanging Success !");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if (jComboBox4.getSelectedItem().equals("Unregisterd")) {
            jTextField13.setText("Null");
            jTextField13.setEnabled(false);

        } else {
            jTextField13.setEnabled(true);

        }
    }//GEN-LAST:event_jComboBox4ActionPerformed
int modeldif;
int mileagedif,cusprice,sysprice;
double tot;
    public void calculation()
            
    {
        modeldif=Integer.parseInt(jLabel14.getText())-Integer.parseInt(jTextField9.getText());
        mileagedif=Integer.parseInt(jLabel20.getText())-Integer.parseInt(jTextField9.getText());
        cusprice=Integer.parseInt(jTextField15.getText());
          sysprice=Integer.parseInt(jLabel28.getText());
         if (jComboBox1.getSelectedItem().equals("Toyota"))
         {
      if(mileagedif>0)
      {
          if(modeldif==0)
          {
            cusprice=cusprice+cusprice*20/100;
          tot=sysprice-cusprice;
       jLabel57.setText(Double.toString(tot));
          }
      }
    }
         
         else if(mileagedif<0)
         {
             if(modeldif==0)
             {
                  cusprice=cusprice+cusprice*5/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
             else if(modeldif<0)
             {
                 cusprice=cusprice-cusprice*9/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
             
         }
           if (jComboBox1.getSelectedItem().equals("Nissan"))
         {
      if(mileagedif>0)
      {
          if(modeldif==0)
          {
            cusprice=cusprice+cusprice*10/100;
          tot=sysprice-cusprice;
       jLabel57.setText(Double.toString(tot));
          }
      }
    }
         
         else if(mileagedif<0)
         {
             if(modeldif==0)
             {
                  cusprice=cusprice+cusprice*8/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
             else if(modeldif<0)
             {
                 cusprice=cusprice-cusprice*12/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
             
         }
         else if(modeldif<=5)
         {
             if(mileagedif>100000)
             {
                  cusprice=cusprice+cusprice*22/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
             else if(mileagedif>10000)
             {
                  cusprice=cusprice-cusprice*25/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
             }
         }
         else if(modeldif>5)
         {
              cusprice=cusprice-cusprice*13/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
         }
         
         else if(modeldif<-10)
         {
             if (jComboBox1.getSelectedItem().equals("TOYOTA"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
           else  if (jComboBox1.getSelectedItem().equals("NISSAN"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
            else if (jComboBox1.getSelectedItem().equals("MAZDA"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
            else if (jComboBox1.getSelectedItem().equals("BMW"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
           else  if (jComboBox1.getSelectedItem().equals("WOLKSWAGON"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
             if (jComboBox1.getSelectedItem().equals("MITSUBISHI"))
             {
                 if(mileagedif<-100000)
                 {
                     cusprice=cusprice-cusprice*15/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else if(mileagedif<-200000)
                 {
                         cusprice=cusprice-cusprice*20/100;
                  tot=sysprice-cusprice;
                  jLabel57.setText(Double.toString(tot));
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "mileage difference gap  is higher price will be higher in system vehicle");
                 }
             }
         }
           
           
           
           if(tot<0)
           {
               JOptionPane.showMessageDialog(null, "Company Must give this sum of money");
           }
           else{
               JOptionPane.showMessageDialog(null, "Customer Must give this sum of money");
           }
           
           
    }
    
    String path1;
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        
        String exPath = "C:\\Users\\it17153232\\Desktop\\Vehicle Sale Project\\Project\\VehicleSalesManagement\\src\\Reports\\ExchangingReport.jrxml";
        try {
            Map pr = new HashMap();
            
            
                  pr.put("b", jLabel12.getText());
                  pr.put("my", jLabel14.getText());
                  pr.put("mo", jLabel16.getText());
                  
                   pr.put("engC",jLabel18.getText());
                   pr.put("milea",jLabel20.getText());
                   
                   
                  
                   pr.put("price",jLabel28.getText());
                   pr.put("type",jLabel30.getText());
                   pr.put("status",jLabel32.getText());
                  
                   pr.put("eBrand",jComboBox1.getSelectedItem());
                   pr.put("eModelYear",jTextField9.getText());
                   pr.put("eModel",jComboBox2.getSelectedItem());
                   pr.put("eEngC",jTextField10.getText());
                   pr.put("eMileage",jTextField11.getText());
                   
                   
                   pr.put("ePrice",jTextField15.getText());
                   pr.put("eType",jComboBox3.getSelectedItem());
                    pr.put("eStatus",jComboBox4.getSelectedItem());
                    
               pr.put("img",imgp);
               pr.put("img2", path);
               
               pr.put("sp",jLabel28.getText());
               pr.put("ep",jTextField15.getText());
               pr.put("minb", jLabel57.getText());
                

            if (Double.valueOf(jLabel57.getText()) < 0) {

                pr.put("des","You have want to pay"+jLabel57.getText());

            } else if (Double.valueOf(jLabel57.getText()) == 0) {

                pr.put("des", "Customer have want to pay"+jLabel57.getText());
               
                

            }else{
                pr.put("des", "Exchange only");
            
            }
            
   
            
            
            

            JREmptyDataSource ds = new JREmptyDataSource();
            JasperReport jr3 = JasperCompileManager.compileReport(exPath);
            JasperPrint jasperP = JasperFillManager.fillReport(jr3, pr, ds);//set 2nd param map
            JasperViewer.viewReport(jasperP, false);
            } catch (JRException ex) {
            ex.printStackTrace();
           
        }
        


    }//GEN-LAST:event_jButton8ActionPerformed

    private void REGISTERDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERDActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

   VolatileImage msg=jTable1.createVolatileImage(60, 60);
        new ExchangeTable(msg).setVisible(true);
        
        
        
        
        
        
  
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        try {
            ResultSet rs = Database.getData("SELECT * FROM exchangeveh ");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString(2));
                
                v.add (rs.getString(3));
                
               //year
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getDouble(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));
                 v.add(rs.getString(1));
                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }



    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
try{
Process p=Runtime.getRuntime().exec("C:\\Windows\\System32\\calc.exe");
JFrame j=new JFrame();
p.equals(j);
    }//GEN-LAST:event_jButton10MouseClicked
catch(Exception e)
{
    
}
    }
  
    public void refresh()
    {
        jComboBox1.getSelectedItem().equals(null);
        jComboBox2.getSelectedItem().equals(null);
    }
    
    
    
    
    
    
    
    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
       // engNumber = jTextField1.getText();
        long count = 0;
  
        try {
         
  String selected = (String)jComboBox1.getSelectedItem();

        if(selected.equals("MITSUBISHI"))
   {             
                    //System.out.println("Testing Sucess");
                     jTextField9.setText("2015");
                   jTextField10.setText("1600");
                   jTextField11.setText("120000");
                   jTextField12.setText("CH222224400");
                   jTextField13.setText("CAB-6600");
                   jTextField14.setText("EN77889955");
                   jTextField15.setText("670000");
                   jTextArea2.setText("all/power Shutters/Power Mirrors");

   }
        else if(selected.equals("TOYOTA")){
        jTextField9.setText("2012");
                   jTextField10.setText("1800");
                   jTextField11.setText("220000");
                   jTextField12.setText("CH55555588");
                   jTextField13.setText("KI-6600");
                   jTextField14.setText("EN66666660");
                   jTextField15.setText("2700000");
                   jTextArea2.setText("all/power Shutters/Power Mirrors");
   }
         else if(selected.equals("NISSAN")){
        jTextField9.setText("2014");
                   jTextField10.setText("3000");
                   jTextField11.setText("220000");
                   jTextField12.setText("CH77774444");
                   jTextField13.setText("KM-6754");
                   jTextField14.setText("EN77444444");
                   jTextField15.setText("2970000");
                   jTextArea2.setText("all/power Shutters/Power Mirrors");
   }
        
        else{
       
            jTextField9.setText(null);
             jTextField10.setText(null);
                   jTextField11.setText(null);
                   jTextField12.setText(null);
                   jTextField13.setText(null);
                   jTextField14.setText(null);
                   jTextField15.setText(null);
                   jTextArea2.setText(null);
                   JOptionPane.showMessageDialog(null, "Invalid");
        }
    }    

         catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped

    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed

    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Brand().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         new Model().setVisible(true);
         refresh();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton REGISTERD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables

    private void brandload() {

        try {
            ResultSet rs = Database.getData("select Brand_name from Brand GROUP BY Brand_name  ASC  ");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("Brand_name"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void typeload() {
        jComboBox3.addItem("Car");
        jComboBox3.addItem("Van");
        jComboBox3.addItem("Bus");
        jComboBox3.addItem("Truck");
        jComboBox3.addItem("Lorry");
        jComboBox3.addItem("Jeep");
    }

    private void statusload() {
        jComboBox4.addItem("Registerd");
        jComboBox4.addItem("Unregisterd");

    }

    private void customerload() {
        try {

            ResultSet rs = Database.getData("select * from customer");
            while (rs.next()) {

                jComboBox5.addItem(rs.getString(3));

            }

        } catch (Exception e) {
        }
    }

    private void registerdCount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from vehicle where status='Registerd'");
            while (rs.next()) {
                jLabel64.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }
    }

    private void unregisterdcount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from vehicle where status='Unregistered'");
            while (rs.next()) {
                jLabel65.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }

    }

    private void exchangecount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from exchangeveh");
            while (rs.next()) {
                jLabel66.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }
    }

    
}
